services:
  minecraft:
    image: ghcr.io/ldg030201/mc-server:latest
    pull_policy: always
    container_name: mc-ms
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.16.5"
      FORGE_VERSION: "36.2.39"
      MEMORY: "6G"
      TZ: "Asia/Seoul"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: 25575
    tty: true
    stdin_open: true
    volumes:
      - mc-data:/data
      - ./user/mods:/mods:ro

  teg-admin:
    image: ghcr.io/ldg030201/teg-admin:latest
    pull_policy: always
    container_name: teg-admin
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mc-data:/mc-data:ro
    environment:
      RCON_HOST: minecraft
      RCON_PORT: 25575
      RCON_PASSWORD: "${RCON_PASSWORD}"
      MC_CONTAINER_NAME: mc-ms
    depends_on:
      - minecraft

volumes:
  mc-data:
